// Activități — lucruri de FĂCUT, nu locuri de văzut.
//
// Diferența contează la vot: „mergem la Balos" și „facem o degustare de vinuri"
// sunt întrebări separate, iar amestecate într-o singură listă se sufocă una pe
// alta.
//
// Nu numesc firme pe care nu le-am verificat. Unde e nevoie de un operator,
// scrie cum se găsește, nu pe cine să sunați.

export const CATEGORII_ACTIVITATI = {
  apa: { eticheta: 'Pe apă', emoji: '🌊' },
  gust: { eticheta: 'De gustat', emoji: '🍷' },
  seara: { eticheta: 'Seara', emoji: '🌙' },
  local: { eticheta: 'Cu localnicii', emoji: '🫒' },
  adrenalina: { eticheta: 'Cu motor', emoji: '🏍️' },
};

export const ACTIVITATI = [
  {
    id: 'act-degustare-vin',
    fel: 'activitate',
    nume: 'Degustare de vinuri la o cramă',
    categorie: 'gust',
    zona: 'centru',
    subtitlu: 'Peza și Archanes, lângă Knossos',
    durata: '2–3 h',
    costText: '15–30 €/persoană, cu degustare și mezeluri',
    deCe: 'Creta are soiuri care nu cresc nicăieri altundeva — vilana la alb, kotsifali și mandilaria la roșu. Cramele din Peza și Archanes sunt la 20 de minute de Knossos, iar degustările se fac în curți umbrite de viță sau în pivnițe de piatră. **În septembrie e cules**, deci prindeți crama în plină activitate.',
    cumFaci: 'Se sună dimineața pentru după-amiaza aceea; majoritatea primesc și fără programare, dar un grup de șapte merită anunțat. Se combină firesc cu Knossos, joi.',
    capcane: 'Cineva trebuie să rămână treaz la volan — și ăla e Bengi, singurul pe contract. Alegeți crama după cine conduce, nu invers.',
    deLuat: 'Loc în portbagaj: sticlele cumpărate acolo sunt jumătate din prețul de la aeroport.',
  },
  {
    id: 'act-jetski',
    fel: 'activitate',
    nume: 'Jet ski safari',
    categorie: 'adrenalina',
    zona: 'ambele',
    subtitlu: 'Cerut de grup — golfuri la care nu ajunge nimeni altcineva',
    durata: '1–2 h',
    costText: '~60–120 € de jet ski (doi pe unul), în funcție de durată',
    deCe: 'Nu e închiriere de zece minute în fața plajei, ci un traseu cu ghid de-a lungul coastei: se intră în golfuri fără drum de acces, se oprește la o plajă la care se ajunge doar pe mare, și se face cale-ntoarsă. Cu șapte oameni ies trei-patru jet ski-uri, deci merge ca activitate de grup.',
    cumFaci: 'Se găsește pe plajele organizate mari — Platanias și Agia Marina în vest, Elounda și Amoudara în est. Se rezervă cu o zi înainte pentru un grup. **Nu e nevoie de permis nautic** pentru safari cu ghid.',
    capcane: 'Se anulează la vânt și se face doar dimineața, cât marea e plată. Verificați ce acoperă asigurarea înainte să semnați. Cine n-a mai condus urcă în spate, nu în față.',
    deLuat: 'Ochelari care nu zboară, cremă rezistentă la apă, săculeț etanș pentru telefon. Nu luați nimic ce nu suportă apă sărată.',
  },
  {
    id: 'act-quad',
    fel: 'activitate',
    nume: 'Safari cu quad-uri (ATV)',
    categorie: 'adrenalina',
    zona: 'ambele',
    subtitlu: 'Drumuri de pământ pe care mașina închiriată n-are voie',
    durata: '4–6 h',
    costText: '~70–100 € de quad (doi pe unul), de obicei cu masă inclusă',
    deCe: 'Exact drumurile pe care contractul Eurocars vi le interzice: poteci de pământ prin munte, sate în care nu intră autocarele, peșteri și platouri. Turele bune includ și o masă cretană la o tavernă de sat. E cea mai bună cale de a vedea interiorul insulei fără să riscați mașina.',
    cumFaci: 'Se rezervă printr-o agenție locală sau prin cazare, cu o zi-două înainte. Permisul de conducere e obligatoriu pentru cine conduce.',
    capcane: 'Praf, mult. Se vine cu haine care pot fi aruncate la spălat, nu cu ce vreți să purtați seara. Cască obligatorie. Cine conduce nu bea la masa de la mijloc.',
    deLuat: 'Ochelari, batic sau bandană pentru praf, haine vechi, pantofi închiși.',
  },
  {
    id: 'act-cai',
    fel: 'activitate',
    nume: 'Călărie în munții Finikia și Giouchtas',
    categorie: 'local',
    zona: 'centru',
    subtitlu: 'Pe cai, acolo unde nu ajung mașinile',
    durata: 'Ziua întreagă, cu masă',
    costText: '~90–120 €/persoană, cu prânz și transfer',
    deCe: 'Tur de o zi pe versanții munților Finikia și Giouchtas, lângă Heraklion — poteci pe care nu se poate ajunge cu nimic pe roți. Include o oprire de răcoritoare în vârf și un prânz cretan cu vinul casei la final. Se face și de începători, nu doar de cine a mai călărit.',
    cumFaci: 'Se rezervă online, din timp — e o tură cu locuri limitate. Include de obicei transfer de la hoteluri alese.',
    capcane: 'Zi întreagă, deci intră în concurență cu orice altceva. Zona e lângă Heraklion, adică departe de ambele cazări — cel mai bine se leagă cu ziua de joi, dacă mutați planul.',
    deLuat: 'Pantaloni lungi, pantofi închiși cu toc mic, pălărie.',
  },
  {
    id: 'act-samaria-ghid',
    fel: 'activitate',
    nume: 'Samaria cu ghid, plecare din Chania',
    categorie: 'local',
    zona: 'vest',
    subtitlu: 'Varianta care rezolvă logistica',
    durata: 'Ziua întreagă, 11–12 h',
    costText: '~40–60 €/persoană, cu transport și ferry',
    deCe: 'Problema cu Samaria nu e mersul, e logistica: 16 km într-o singură direcție, ieșire pe mare la Agia Roumeli, ferry la Chora Sfakion, autocar înapoi — iar mașina rămâne toată ziua în partea greșită a muntelui. **Cu un tur ghidat dispare toată partea asta**: pleci din Chania și te întorci în Chania, iar între timp ai un om care știe traseul.',
    cumFaci: 'Se rezervă din Chania, cu o zi-două înainte. Plecarea e pe la 06:00 dimineața.',
    capcane: 'Tot 16 km și 1.230 m de coborâre rămân — genunchii nu-i salvează niciun ghid. Cu șapte oameni de forme diferite, grupul se rupe oricum.',
    deLuat: 'Doar dacă tot grupul vrea Samaria. Altfel, cheile Imbros dau aceeași senzație în trei ore.',
  },
  {
    id: 'act-ulei',
    fel: 'activitate',
    nume: 'Degustare de ulei de măsline',
    categorie: 'gust',
    zona: 'ambele',
    subtitlu: 'Se gustă ca vinul, și se învață diferența',
    durata: '1–2 h',
    costText: '10–20 €/persoană; gratis la unele mănăstiri',
    deCe: 'Uleiul cretan e printre cele mai bune din lume, iar diferența dintre unul bun și unul obișnuit se simte abia când le pui unul lângă altul. La Peskesi, joi, se poate cere direct la masă o degustare de uleiuri — e recomandarea casei.',
    cumFaci: 'Mănăstirea Agia Triada (Akrotiri) vinde uleiul propriu la poartă. La Peskesi se comandă din meniu.',
    capcane: 'Uleiul bun nu se ia de la supermarket, ci de la producător sau de la mănăstire.',
    deLuat: 'O sticlă adusă acasă e cel mai bun suvenir posibil — dar trebuie să meargă în bagajul de cală.',
  },
  {
    id: 'act-muzica',
    fel: 'activitate',
    nume: 'O seară cu muzică cretană live',
    categorie: 'seara',
    zona: 'ambele',
    subtitlu: 'Liră, lăută și raki până târziu',
    durata: 'O seară',
    costText: 'Cât mâncarea; de obicei fără taxă separată',
    deCe: 'Muzica cretană nu e folclor pentru turiști — se cântă la liră și lăută, oamenii se ridică și dansează, iar serile astea țin până dimineață. E cel mai aproape de a intra în viața locului fără să cunoști pe nimeni.',
    cumFaci: 'Se întreabă la cazare care tavernă are muzică în seara aceea; se schimbă de la o zi la alta. În Chania, în orașul vechi, sunt câteva locuri cu program fix.',
    capcane: 'Începe târziu — pe la 22:00–23:00. Nu e o seară de făcut înainte de o zi cu trezire la 07:00.',
    deLuat: 'Răbdare cu rachiul care se tot aduce la masă.',
  },
  {
    id: 'act-snorkeling',
    fel: 'activitate',
    nume: 'Snorkeling',
    categorie: 'apa',
    zona: 'ambele',
    subtitlu: 'Apa e limpede până la 20 de metri',
    durata: '1–2 h',
    costText: 'Gratis, dacă vă luați măștile de acasă',
    deCe: 'În septembrie apa e la 25 °C și e cea mai limpede din an. La Seitan Limania, Kamini și Mochlos se vede fundul de la suprafață, cu pești, caverne mici și, pe alocuri, pietre lucrate de om acum câteva mii de ani.',
    cumFaci: 'Cel mai ieftin e să aduceți două-trei măști de acasă. Se găsesc și pe loc, la 10–15 € bucata.',
    capcane: 'Nu intrați singuri în golfuri fără ieșire ușoară. Papucii de apă sunt obligatorii pe pietre.',
    deLuat: 'Măști și tuburi în bagaj — ocupă puțin și se folosesc în fiecare zi.',
  },
  {
    id: 'act-caiac',
    fel: 'activitate',
    nume: 'Caiac sau SUP pe mare',
    categorie: 'apa',
    zona: 'ambele',
    subtitlu: 'Golfuri la care nu se ajunge pe uscat',
    durata: '2–3 h',
    costText: '15–25 €/persoană pe oră sau două',
    deCe: 'Coasta are zeci de golfuri mici la care nu duce niciun drum. Cu un caiac ajungi în ele în douăzeci de minute și rămâi singur pe o plajă care n-are nume.',
    cumFaci: 'Se închiriază de pe plajele organizate — Platanias, Kolymbari în vest, Amoudara și Elounda în est. Nu e nevoie de rezervare.',
    capcane: 'Dimineața marea e plată, după-amiaza se ridică vântul. Plecați devreme.',
    deLuat: 'Cremă rezistentă la apă și un săculeț etanș pentru telefon.',
  },
  {
    id: 'act-apus-barca',
    fel: 'activitate',
    nume: 'Ieșire cu barca la apus',
    categorie: 'apa',
    zona: 'ambele',
    subtitlu: 'Două ore, cu soarele intrând în mare',
    durata: '2–3 h',
    costText: '25–40 €/persoană',
    deCe: 'Altceva decât barca de zi: se pleacă pe la 18:00, se oprește undeva pentru o baie, și se privește apusul din larg. În vest, cu Falassarna sau Gramvousa în spate, e greu de bătut.',
    cumFaci: 'Se găsesc în porturile mici — Kissamos, Kolymbari, Elounda, Agios Nikolaos. Se rezervă cu o zi înainte.',
    capcane: 'Se anulează la vânt. Întrebați dimineața.',
    deLuat: 'Ceva peste tricou: pe apă, după apus, se răcește repede.',
  },
  {
    id: 'act-gatit',
    fel: 'activitate',
    nume: 'Curs de gătit cretan',
    categorie: 'gust',
    zona: 'ambele',
    subtitlu: 'Se gătește, apoi se mănâncă ce ai gătit',
    durata: '4–5 h',
    costText: '60–90 €/persoană',
    deCe: 'De obicei începe cu o plimbare prin grădină sau prin piață, continuă cu gătitul a patru-cinci feluri și se termină cu masa, la o masă lungă, cu vinul casei. Pentru șapte oameni care oricum gătesc împreună în vilă, e o zi întreagă de amintiri.',
    cumFaci: 'Se caută „Cretan cooking class" pentru zona în care sunteți; se rezervă cu câteva zile înainte, mai ales pentru un grup de șapte.',
    capcane: 'E scump și mănâncă o jumătate de zi. Merită doar dacă tot grupul vrea.',
    deLuat: 'Poftă, și haine care suportă ulei de măsline.',
  },
  {
    id: 'act-cinema',
    fel: 'activitate',
    nume: 'Cinema în aer liber',
    categorie: 'seara',
    zona: 'vest',
    subtitlu: 'Film sub stele, cu bere rece',
    durata: '2–3 h',
    costText: '~8 €/bilet',
    deCe: 'Grecii au păstrat cinematografele de vară: curți cu ziduri, scaune de grădină, un ecran alb și un bar. Filmele sunt în original, cu subtitrare greacă. În Chania e unul în grădina publică, care funcționează până la începutul lui octombrie.',
    cumFaci: 'Se caută programul zilei pe loc; biletele se iau la intrare.',
    capcane: 'Începe după ce se întunecă bine, pe la 21:00–21:30.',
    deLuat: 'O bluză — grădina se răcorește.',
  },
  {
    id: 'act-stele',
    fel: 'activitate',
    nume: 'Baie de noapte și stele',
    categorie: 'seara',
    zona: 'ambele',
    subtitlu: 'Gratis, și nimeni nu-l uită',
    durata: '1–2 h',
    costText: 'Gratis',
    deCe: 'Marea rămâne caldă mult după ce aerul se răcește, iar în septembrie cerul e curat. La zece minute pe jos de ambele cazări se ajunge la o plajă goală, unde noaptea nu e nicio lumină în afară de sat.',
    cumFaci: 'Se merge pe jos, după cină. Nimic de rezervat.',
    capcane: 'Nu intrați departe pe întuneric și nu singuri. Lăsați o lanternă aprinsă pe prosoape, ca să știți unde e malul.',
    deLuat: 'Prosoape, o lanternă, și telefoanele lăsate în geantă.',
  },
  {
    id: 'act-stana',
    fel: 'activitate',
    nume: 'O stână și brânza făcută pe loc',
    categorie: 'local',
    zona: 'ambele',
    subtitlu: 'Munte, capre, mizithra proaspătă',
    durata: '2–3 h',
    costText: '20–35 €/persoană, cu masă',
    deCe: 'Sus, pe platourile de munte, ciobanii cretani fac graviera și mizithra ca acum o sută de ani. Câțiva primesc vizitatori: vezi mulsul, cum se leagă brânza, și mănânci la masa lor. Pe platoul Lasithi și în satele din spatele Chaniei sunt cele mai multe.',
    cumFaci: 'Se aranjează prin cazare sau printr-o tavernă de sat — nu prin agenții.',
    capcane: 'Drumuri de munte înguste, uneori de pământ. Cu Caddy-ul, întrebați starea drumului înainte.',
    deLuat: 'Pantofi închiși, și stomac gol.',
  },
  {
    id: 'act-olarit',
    fel: 'activitate',
    nume: 'Olărit la Margarites',
    categorie: 'local',
    zona: 'vest',
    subtitlu: 'Satul olarilor, de 500 de ani',
    durata: '2 h',
    costText: 'Gratis de privit; 20–30 € un atelier scurt',
    deCe: 'Un sat de munte în care se face ceramică de cinci secole, cu ateliere deschise în care meșterii lucrează la roată în fața ta. Câțiva te pun să încerci. E la 30 de minute de Rethymno, deci prinde ziua de marți.',
    cumFaci: 'Se intră pur și simplu în ateliere. Pentru un atelier practic, se întreabă pe loc.',
    capcane: 'Ce cumperi trebuie să ajungă acasă întreg — cereți ambalaj bun.',
    deLuat: 'O oprire în plus pe drumul de marți, dacă renunțați la altceva.',
  },
  {
    id: 'act-piata',
    fel: 'activitate',
    nume: 'Piața din Chania, dimineața',
    categorie: 'local',
    zona: 'vest',
    subtitlu: 'Hala municipală, în formă de cruce',
    durata: '1–2 h',
    costText: 'Cât cumpărați',
    deCe: 'O hală din 1913, în formă de cruce, cu măcelării, brânzeturi, ierburi de munte, miere și raki de casă. E locul unde se cumpără cel mai bine ce duceți acasă, și unde vedeți ce mănâncă de fapt lumea de aici.',
    cumFaci: 'Dimineața, până la 14:00. Închisă duminica.',
    capcane: 'Tarabele de la intrare sunt pentru turiști; cele bune sunt în brațele laterale.',
    deLuat: 'Ierburi de munte, miere de cimbru, graviera — toate rezistă la drum.',
  },
];

export function activitatea(id) {
  return ACTIVITATI.find((a) => a.id === id) || null;
}

export function activitatiPeZona(zona) {
  return ACTIVITATI.filter((a) => a.zona === zona || a.zona === 'ambele');
}
