// Locurile. Fiecare fișă are ce trebuie ca să iei o decizie dimineața, la
// cafea: cât se conduce, cât costă, cât ține, de ce merită și ce te încurcă.
//
// `dinVest` / `dinEst` sunt minutele de condus din baza respectivă (Maleme,
// respectiv Amoudara). Unde scrie null, locul nu e realist din baza aceea.
// Timpii sunt pentru septembrie, fără trafic de vârf.

export const ZONE = {
  vest: { eticheta: 'Vest — din Maleme', baza: 'Maleme' },
  est: { eticheta: 'Est — din Amoudara', baza: 'Amoudara' },
  centru: { eticheta: 'Centru — Heraklion', baza: 'Heraklion' },
};

export const TIPURI = {
  plaja: { eticheta: 'Plajă', emoji: '🏖️' },
  barca: { eticheta: 'Cu barca', emoji: '⛵' },
  munte: { eticheta: 'Munte și chei', emoji: '⛰️' },
  sat: { eticheta: 'Sat și oraș', emoji: '🏘️' },
  istorie: { eticheta: 'Istorie', emoji: '🏛️' },
  natura: { eticheta: 'Natură', emoji: '🌿' },
};

export const LOCURI = [
  // ───────────────────────────── VEST ─────────────────────────────
  {
    id: 'balos',
    nume: 'Balos și Gramvousa',
    tip: 'barca',
    zona: 'vest',
    vedeta: true,
    dinVest: 40, dinEst: null,
    subtitlu: 'Laguna care apare pe toate afișele cu Creta',
    durata: 'Ziua întreagă',
    costCenti: 4100,
    costText: '41 €/adult (40 € barca + 1 € taxă municipală)',
    deCe: 'Trei mări care se întâlnesc într-o lagună cu apă turcoaz și nisip alb, cu insula-cetate Gramvousa alături. E locul cel mai fotografiat din Creta și, în septembrie, chiar se poate sta liniștit pe el.',
    cumAjungi: 'Barca din portul Kissamos: plecare 10:35, întoarcere 17:45. Include 2 h la Gramvousa și 2 h 30 min la Balos.',
    capcane: 'Drumul de pământ spre Balos e interzis de contractul de închiriere și anulează asigurarea. Nu-l luați. Pe Gramvousa urcarea la cetate e 20 de minute în soare, fără umbră.',
    deLuat: 'Apă multă, pălărie, papuci de apă, bani cash pentru bufetul de pe barcă.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Balos+Lagoon+Crete',
  },
  {
    id: 'elafonisi',
    nume: 'Elafonisi',
    tip: 'plaja',
    zona: 'vest',
    vedeta: true,
    dinVest: 100, dinEst: null,
    subtitlu: 'Nisip roz și o lagună până la genunchi',
    cerut: true,
    durata: 'Ziua întreagă',
    costCenti: 0,
    costText: 'Gratis; parcarea ~4 €, șezlong ~8 €',
    deCe: 'Cea mai cunoscută plajă din Creta, și singura cu **nisip roz**: culoarea vine din milioane de scoici Foraminifera sfărâmate de valuri, iar nuanța e cea mai tare pe limba de nisip dinspre insuliță și după ce trece un val. Laguna e întinsă, caldă și mică de adâncime — se trece pe jos prin apă până pe insulița din față.',
    cumAjungi: '~75 km din Maleme, dar 1 h 40 min – 2 h de condus: drumul trece prin cheile Topolia, cu tunel îngust și serpentine strânse.',
    capcane: 'Drumul e obositor pentru șofer și cu rău de mașină pentru ceilalți. În septembrie vântul de sud poate ridica valuri și alge. Recomandarea gazdei spune „1 oră" — nu e realist, socotiți două.',
    deLuat: 'Plecare dimineață. Pungi pentru rău de mașină, dacă cineva e sensibil. **Nisipul roz nu se ia acasă** — e interzis și amendabil, zona e rezervație Natura 2000.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Elafonisi+Beach+Crete',
  },
  {
    id: 'falassarna',
    nume: 'Falassarna',
    tip: 'plaja',
    zona: 'vest',
    vedeta: true,
    cerut: true,
    dinVest: 40, dinEst: null,
    subtitlu: 'Cinci plaje și cel mai bun apus din insulă',
    durata: 'Jumătate de zi sau seara',
    costCenti: 0,
    costText: 'Gratis; șezlonguri ~8 €/set',
    deCe: 'O bandă lungă de nisip orientată spre vest, cu orizontul liber — de aici se vede cel mai bun apus din Creta. Nu e o singură plajă, ci cinci, fiecare cu alt caracter; se merge până se găsește una goală.',
    cumAjungi: '40 de minute din Maleme, drum bun, asfalt până la parcare.',
    capcane: 'Fiind deschisă spre vest, prinde val și vânt când suflă dinspre larg. Cu val mare, apa e tulbure.',
    deLuat: 'Ceva de mâncare pentru apus — merită stat până la capăt.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Falassarna+Beach+Crete',
  },
  {
    id: 'chania',
    nume: 'Orașul vechi din Chania',
    tip: 'sat',
    zona: 'vest',
    vedeta: true,
    dinVest: 25, dinEst: null,
    subtitlu: 'Portul venețian, seara',
    durata: 'O seară',
    costCenti: 0,
    costText: 'Gratis de umblat',
    deCe: 'Cel mai frumos oraș vechi din Creta: port venețian cu far, ulițe înguste venețiene și turcești, un fost hammam devenit restaurant, zidurile cetății. Seara se umple de lume, într-un mod plăcut.',
    cumAjungi: '25 de minute din Maleme. Parcare cu plată în afara orașului vechi — înăuntru nu se intră cu mașina.',
    capcane: 'Restaurantele de pe cheiul principal sunt scumpe și mediocre; cele bune sunt la o stradă în spate (Splantzia).',
    deLuat: 'Ceva peste tricou — seara, lângă apă, se răcește.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Chania+Old+Town',
  },
  {
    id: 'imbros',
    nume: 'Cheile Imbros',
    tip: 'munte',
    zona: 'vest',
    vedeta: true,
    dinVest: 65, dinEst: null,
    subtitlu: 'Traseul montan care încape într-o zi',
    durata: '2–3 h de mers, 5–6 h cu drumul',
    costCenti: 300,
    costText: '~3 €/persoană intrarea',
    deCe: 'Opt kilometri de defileu cu pereți care se strâng până la doi metri unul de altul. Coborâre continuă, fără nimic tehnic — se face în adidași. E varianta sănătoasă la Samaria: aceeași senzație de canion, fără o zi întreagă de logistică.',
    cumAjungi: 'Se pornește din satul Imbros (~1 h din Maleme, prin Vrisses) și se coboară la Komitades. Un taxi vă aduce înapoi la mașină, ~15–20 €, sau se lasă cineva la capătul de jos.',
    capcane: 'Traseul e într-o singură direcție — mașina rămâne sus. Fixați întoarcerea înainte de a porni. Nu are apă pe traseu.',
    deLuat: 'Minimum 1,5 l de apă de om, adidași cu talpă bună (pietriș rulant), pălărie.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Imbros+Gorge+Crete',
  },
  {
    id: 'samaria',
    nume: 'Cheile Samaria',
    tip: 'munte',
    zona: 'vest',
    dinVest: 90, dinEst: null,
    subtitlu: 'Traseul celebru — dar mâncă ziua întreagă',
    durata: '5–7 h de mers, 11–12 h cu tot drumul',
    costCenti: 500,
    costText: '5 € intrarea + ~12 € ferry + autocar',
    deCe: 'Cel mai lung defileu din Europa: 16 km, cu 1.230 m de coborâre și „Porțile", unde pereții se apropie la trei metri. E o realizare, nu o plimbare.',
    cumAjungi: 'Complicat, și de asta nu îl recomand cu mașina proprie: se intră pe sus (Xyloskalo), se iese la Agia Roumeli pe mare, de acolo ferry la Chora Sfakion, apoi autocar înapoi la mașină. Mașina rămâne toată ziua în partea greșită a muntelui.',
    capcane: 'Coborârea de 1.230 m distruge genunchii, nu distanța. Cu șapte oameni de forme diferite, grupul se rupe. Ultimul ferry nu așteaptă.',
    deLuat: 'Doar dacă tot grupul vrea asta și acceptă să piardă restul zilei.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Samaria+Gorge',
  },
  {
    id: 'seitan',
    nume: 'Seitan Limania',
    tip: 'plaja',
    zona: 'vest',
    ascuns: true,
    cerut: true,
    dinVest: 45, dinEst: null,
    subtitlu: 'Un fiord între pereți abrupți de stâncă',
    durata: '3–4 h',
    costCenti: 0,
    costText: 'Gratis',
    deCe: 'O crăpătură în stâncă, plină cu apă de un turcoaz aproape fals, între **pereți abrupți de calcar alb care cad drept în mare**. Golful e îngust și adânc, ca un fiord, iar stâncile de deasupra au zeci de metri. Arată ca o fotografie prelucrată și nu e.',
    cumAjungi: 'Drum asfaltat până la parcarea de sus, apoi 10–15 minute de coborâre pe o potecă abruptă, cu pietre.',
    capcane: '**Pereții sunt abrupți și poteca merge pe marginea lor** — coborârea e serioasă: pietriș rulant, fără balustradă, nu merge în șlapi și nu e de lăsat copiii înainte. Plaja e mică și se umple repede. Nicio umbră, nicio apă, nicio tavernă.',
    deLuat: 'Adidași pentru coborâre, apă, și venit dimineața devreme.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Seitan+Limania+Crete',
  },
  {
    id: 'kolymbari',
    nume: 'Kolymbari',
    tip: 'sat',
    zona: 'vest',
    dinVest: 10, dinEst: null,
    subtitlu: 'Satul de pescari de lângă voi',
    durata: 'O seară',
    costCenti: 0,
    costText: 'Gratis',
    deCe: 'La zece minute de cazare: un port mic, o plajă cu pietriș, câteva taverne cu pește și zero autocare. Varianta pentru seara în care nimeni nu mai vrea să conducă.',
    cumAjungi: '10 minute pe drumul de coastă.',
    capcane: 'Plaja e cu pietre, nu cu nisip.',
    deLuat: 'Nimic.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Kolymbari+Crete',
  },
  {
    id: 'plaja-hotel',
    nume: 'Plaja de lângă hotel',
    tip: 'plaja',
    zona: 'vest',
    ascuns: true,
    dinVest: 0, dinEst: null,
    subtitlu: 'Recomandarea gazdei: 7 minute pe jos',
    durata: 'Cât vreți',
    costCenti: 0,
    costText: 'Gratis. La Wave, șezlonguri și umbrele gratuite pentru voi',
    deCe: 'Konstantina, gazda, spune: la capătul hotelului la dreapta, 7 minute pe jos, e o plajă excelentă. Iar la stânga e barul Wave, unde hotelul are șezlonguri cu umbrele **gratuite** pentru oaspeți.',
    cumAjungi: 'Pe jos. Fără mașină, fără parcare, fără drum.',
    capcane: 'Niciuna. Asta e ideea.',
    deLuat: 'Prosopul.',
    dinParteaGazdei: true,
  },
  {
    id: 'therisos',
    nume: 'Cheile și satul Therisos',
    tip: 'munte',
    zona: 'vest',
    ascuns: true,
    dinVest: 40, dinEst: null,
    subtitlu: 'Chei pe care le treci cu mașina',
    durata: '3–4 h',
    costCenti: 0,
    costText: 'Gratis',
    deCe: 'Șase kilometri de defileu prin care trece șoseaua, cu pereți verticali de o parte și de alta — se vede fără să cobori din mașină. Sus, satul Therisos, cu taverne de carne la grătar și o istorie de revoltă împotriva turcilor.',
    cumAjungi: '15 minute din Chania, 40 din Maleme. Asfalt tot drumul, dar îngust.',
    capcane: 'Drumul e de o mașină și jumătate pe alocuri, cu vizibilitate scurtă. Claxon la curbe.',
    deLuat: 'Poftă de mâncare — se merge pentru taverne.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Therisos+Gorge+Crete',
  },
  {
    id: 'kournas',
    nume: 'Lacul Kournas',
    tip: 'natura',
    zona: 'vest',
    dinVest: 60, dinEst: 135,
    subtitlu: 'Oprirea perfectă la jumătatea drumului spre est',
    durata: '2–3 h',
    costCenti: 1000,
    costText: 'Gratis; barcă cu pedale ~10 €/jumătate de oră',
    deCe: 'Singurul lac de apă dulce din Creta, verde-turcoaz, într-un căuș de munți. Se închiriază bărci cu pedale, sunt taverne pe mal și broaște țestoase în apă. Cade exact la jumătatea traseului Maleme–Amoudara.',
    cumAjungi: '~1 h din Maleme, chiar lângă ieșirea de la Georgioupoli.',
    capcane: 'La finalul verii nivelul apei scade și marginile rămân mâloase. Tavernele de la intrare sunt de turiști; cele de pe partea opusă sunt mai bune.',
    deLuat: 'Ideal marți, pe drumul spre Agios Nikolaos.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Lake+Kournas+Crete',
  },
  {
    id: 'argiroupoli',
    nume: 'Izvoarele Argiroupoli',
    tip: 'natura',
    zona: 'vest',
    ascuns: true,
    dinVest: 75, dinEst: 120,
    subtitlu: 'Cascade sub platani, la 20 de grade',
    durata: '1–2 h',
    costCenti: 0,
    costText: 'Gratis',
    deCe: 'Un sat cu izvoare care ies direct din stâncă și cad în cascade mici, sub platani bătrâni. Aerul e cu câteva grade mai rece decât pe coastă. Tavernele își țin mesele peste apă și cresc truful în bazine proprii.',
    cumAjungi: '~25 min de la Rethymno, la 10 minute abatere de pe drumul spre est.',
    capcane: 'Se ajunge pe un drum de munte îngust. Locul e mic — o oprire, nu o zi.',
    deLuat: 'O altă opțiune bună de oprire marți.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Argyroupoli+Springs+Crete',
  },
  {
    id: 'rethymno',
    nume: 'Orașul vechi din Rethymno',
    tip: 'sat',
    zona: 'vest',
    dinVest: 75, dinEst: 120,
    subtitlu: 'Fortăreață venețiană și un port mic',
    durata: '2–3 h',
    costCenti: 400,
    costText: 'Gratis de umblat; Fortezza 4 €',
    deCe: 'Un oraș vechi mai mic și mai puțin aglomerat decât Chania, cu o fortăreață venețiană uriașă deasupra mării, un minaret și un port de buzunar. Bun de picioare întinse pe drumul lung de marți.',
    cumAjungi: 'Direct pe drumul național, la jumătatea traseului spre est.',
    capcane: 'Parcarea în centru e grea la ora prânzului.',
    deLuat: 'Bougatsa de la o patiserie din centru.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Rethymno+Old+Town',
  },

  // ───────────────────────────── EST ─────────────────────────────
  {
    id: 'voulisma',
    nume: 'Voulisma (Golden Beach)',
    tip: 'plaja',
    zona: 'est',
    vedeta: true,
    cerut: true,
    dinVest: null, dinEst: 20,
    subtitlu: 'Semilună de nisip fin, steag albastru',
    durata: 'Jumătate de zi',
    costCenti: 0,
    costText: 'Gratis; șezlonguri ~8 €/set',
    deCe: 'Cea mai frumoasă plajă din zona Agios Nikolaos: o semilună de nisip fin și deschis, cu apă care intră în adânc foarte lin și o culoare pe care lumea o compară cu Caraibele. Are steag albastru și e organizată.',
    cumAjungi: '12 km est de Agios Nikolaos, la Istron. ~20 de minute din Amoudara, pe drumul de coastă.',
    capcane: 'Fiind cea mai bună din zonă, se umple. Veniți dimineața. Parcarea de sus e mică.',
    deLuat: 'Nimic special — are tot ce trebuie.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Voulisma+Beach+Istron+Crete',
  },
  {
    id: 'kamini',
    nume: 'Kamini',
    tip: 'plaja',
    zona: 'est',
    ascuns: true,
    cerut: true,
    dinVest: null, dinEst: 30,
    subtitlu: 'Cinci golfuri de pietriș, lângă Gournia',
    durata: '1–2 h',
    costCenti: 0,
    costText: 'Gratis — și nu e nimic de cumpărat',
    deCe: 'Cinci golfuri mici, una după alta, cu pietriș și pereți de calcar, stânci sculptate de apă și peșteri mici. A fost probabil ieșirea la mare a așezării minoice Gournia, care e chiar deasupra. Apă calmă, adâncime medie, și aproape nimeni.',
    cumAjungi: '17 km sud-est de Agios Nikolaos, lângă Pachia Ammos. ~30 de minute din Amoudara.',
    capcane: 'Complet neamenajat: fără șezlonguri, fără umbrele, fără baie, fără apă, fără tavernă. Pietrișul e greu de călcat desculț.',
    deLuat: 'Apă, umbrelă sau prosop mare, papuci de apă. Combinați-o cu Voulisma, care e la cinci minute.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Kamini+Beach+Gournia+Crete',
  },
  {
    id: 'spinalonga',
    nume: 'Spinalonga, cu barca din Plaka',
    tip: 'barca',
    zona: 'est',
    vedeta: true,
    dinVest: null, dinEst: 35,
    subtitlu: 'Plimbarea cu barca de câteva ore',
    durata: '3–4 h în total',
    costCenti: 3200,
    costText: '12 € barca din Plaka + 20 € intrarea pe insulă',
    deCe: 'O cetate venețiană pe o insulă, care a fost până în 1957 colonie de leproși — ultima din Europa. Se umblă pe uliți goale, printre case părăsite, cu Creta la un kilometru și imposibil de atins. E cel mai puternic loc din estul insulei.',
    cumAjungi: 'Din Plaka traversarea e de 10 minute (din Elounda, 20). Bărcile plecă des, de la 9:00–10:00 până la 17:00–18:00. Pe insulă se stă 1 h 30 min – 2 h.',
    capcane: 'Intrarea de 20 € se plătește separat de barcă — mulți se așteaptă să fie inclusă. Nicio umbră pe insulă.',
    deLuat: 'Pălărie, apă, și mâncat în Plaka după, nu înainte.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Spinalonga+Plaka+Crete',
  },
  {
    id: 'agios-nikolaos',
    nume: 'Agios Nikolaos și lacul Voulismeni',
    tip: 'sat',
    zona: 'est',
    dinVest: null, dinEst: 10,
    subtitlu: 'Orașul vostru de seară',
    durata: 'O seară',
    costCenti: 0,
    costText: 'Gratis',
    deCe: 'Un lac aproape rotund, adânc de 64 de metri, legat de mare printr-un canal, cu stânci de o parte și cafenele de alta. În jurul lui se strânge tot orașul seara. E la 10 minute de cazarea din est.',
    cumAjungi: '10 minute din Amoudara.',
    capcane: 'Mesele de pe marginea lacului se plătesc la priveliște, nu la mâncare. Bune pentru o cafea, nu pentru cină.',
    deLuat: 'Nimic.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Lake+Voulismeni+Agios+Nikolaos',
  },
  {
    id: 'plaka-elounda',
    nume: 'Plaka și Elounda',
    tip: 'sat',
    zona: 'est',
    dinVest: null, dinEst: 30,
    subtitlu: 'Două sate cu Spinalonga în față',
    durata: 'O seară',
    costCenti: 0,
    costText: 'Gratis',
    deCe: 'Plaka e un sat mic de pescari, exact în fața insulei Spinalonga — tavernele au mesele pe pietre, cu insula la 500 de metri. Elounda e mai mare și mai lustruită, cu golful ei liniștit. Ideale de combinat cu barca.',
    cumAjungi: '~30 de minute din Amoudara, pe un drum de coastă frumos.',
    capcane: 'Elounda are cele mai scumpe hoteluri din Creta, și prețurile din unele restaurante se potrivesc cu ele.',
    deLuat: 'Rezervare seara, în sezon.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Plaka+Elounda+Crete',
  },
  {
    id: 'lasithi',
    nume: 'Platoul Lasithi și peștera lui Zeus',
    tip: 'munte',
    zona: 'est',
    vedeta: true,
    dinVest: null, dinEst: 60,
    subtitlu: 'Traseul montan din est',
    durata: 'Ziua întreagă',
    costCenti: 600,
    costText: 'Peștera Zeus 6 €',
    deCe: 'Un platou întins la 850 de metri, înconjurat de munți, cu sate de piatră, mori de vânt pentru irigat și câmpuri lucrate ca acum șaptezeci de ani. La Psychro se urcă la peștera în care, spune mitul, s-a născut Zeus. Drumul până sus e spectaculos.',
    cumAjungi: '~1 h din Amoudara, pe serpentine. Se face un tur al platoului cu mașina, opriri în Tzermiado și Agios Georgios.',
    capcane: 'La peșteră se urcă 15–20 de minute pe o potecă pietruită și alunecoasă. Sus e cu 8–10 grade mai răcoare decât pe coastă.',
    deLuat: 'Ceva cu mânecă lungă, pantofi închiși pentru peșteră.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Lasithi+Plateau+Crete',
  },
  {
    id: 'kritsa',
    nume: 'Kritsa și Panagia Kera',
    tip: 'sat',
    zona: 'est',
    ascuns: true,
    dinVest: null, dinEst: 25,
    subtitlu: 'Fresce bizantine în cel mai vechi sat din zonă',
    durata: '2–3 h',
    costCenti: 400,
    costText: 'Panagia Kera 4 €',
    deCe: 'Un sat de munte cu ulițe prea înguste pentru mașini, cunoscut pentru țesături. Pe drum, biserica Panagia Kera are cele mai bine păstrate fresce bizantine din Creta — pictate în secolele XIII–XIV, pe toți pereții.',
    cumAjungi: '12 km în interior de la Agios Nikolaos, ~25 de minute.',
    capcane: 'Biserica e mică și se închide după-amiaza. În sat nu se intră cu mașina — se parchează jos.',
    deLuat: 'De aici pornește drumul spre platoul Katharo, dacă vreți mai departe în munte.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Panagia+Kera+Kritsa+Crete',
  },
  {
    id: 'richtis',
    nume: 'Cheile Richtis și cascada',
    tip: 'munte',
    zona: 'est',
    ascuns: true,
    dinVest: null, dinEst: 60,
    subtitlu: 'Defileu verde cu cascadă de 20 de metri',
    durata: '4–5 h',
    costCenti: 0,
    costText: 'Gratis',
    deCe: 'Cel mai verde traseu din estul Cretei: 3 km de defileu umbrit, cu poduri de piatră, apă care curge tot anul și o cascadă de 20 de metri la capăt. Se termină pe o plajă aproape pustie.',
    cumAjungi: 'Se pornește din satul Exo Mouliana, ~1 h din Amoudara, pe drumul spre Sitia. 2 h 30 min până la cascadă și înapoi.',
    capcane: 'Se trece apa de mai multe ori — picioarele se udă sigur. Pietrele sunt alunecoase. Traseul e marcat slab pe porțiuni.',
    deLuat: 'Papuci de apă sau adidași care pot fi udați, apă, și timp — nu e o plimbare de o oră.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Richtis+Gorge+Crete',
  },
  {
    id: 'mochlos',
    nume: 'Mochlos',
    tip: 'sat',
    zona: 'est',
    ascuns: true,
    dinVest: null, dinEst: 55,
    subtitlu: 'Șapte case, patru taverne, o insuliță minoică',
    durata: '3 h',
    costCenti: 0,
    costText: 'Gratis',
    deCe: 'Un sat de pescari atât de mic încât nu are ce să strice: câteva taverne cu mesele pe plajă și, la 200 de metri în larg, o insuliță cu ruine minoice și morminte care se văd cu ochiul liber. Nimic organizat, nimic pentru turiști.',
    cumAjungi: '~55 de minute din Amoudara, cu o coborâre lungă spre mare.',
    capcane: 'Plaja e cu pietre. Se merge pentru mâncare și liniște, nu pentru înot.',
    deLuat: 'Poftă de pește proaspăt.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Mochlos+Crete',
  },
  {
    id: 'vai',
    nume: 'Plaja Vai',
    tip: 'plaja',
    zona: 'est',
    dinVest: null, dinEst: 105,
    subtitlu: 'Singura pădure de palmieri din Europa',
    durata: 'Ziua întreagă',
    costCenti: 250,
    costText: 'Parcare ~2,50 €; șezlonguri ~8 €',
    deCe: 'Cinci mii de palmieri cretani, o specie care crește doar aici, coborând până la nisipul unei plaje tropicale. Arată ca o eroare de geografie.',
    cumAjungi: '~1 h 45 min din Amoudara, la capătul de est al insulei.',
    capcane: 'Departe. Trei ore și jumătate de condus dus-întors mâncă ziua. Pădurea e împrejmuită, nu se intră printre palmieri.',
    deLuat: 'Doar dacă vreți o zi de drum lung. Voulisma e la 20 de minute și aproape la fel de frumoasă.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Vai+Beach+Crete',
  },
  {
    id: 'amoudara-plaja',
    nume: 'Plaja din Amoudara',
    tip: 'plaja',
    zona: 'est',
    dinVest: null, dinEst: 0,
    subtitlu: 'La ușa cazării din est',
    durata: 'Cât vreți',
    costCenti: 0,
    costText: 'Gratis',
    deCe: 'Plaja satului în care dormiți în ultimele două nopți. Nu e cea mai frumoasă din Creta, dar e la zero minute de mers și e liniștită dimineața.',
    cumAjungi: 'Pe jos.',
    capcane: 'Pietriș pe porțiuni.',
    deLuat: 'Nimic.',
  },

  // ─────────────────────────── CENTRU ───────────────────────────
  {
    id: 'knossos',
    nume: 'Palatul Knossos',
    tip: 'istorie',
    zona: 'centru',
    vedeta: true,
    dinVest: 140, dinEst: 60,
    subtitlu: 'Cel mai vizitat loc din Creta',
    durata: '1 h 30 min – 2 h',
    costCenti: 2000,
    costText: '20 €/adult; 30 € combinat cu Muzeul Arheologic, valabil 3 zile',
    deCe: 'Palatul minoic de acum 3.500 de ani: 22.000 de metri pătrați, vreo 1.300 de încăperi pe mai multe niveluri, coloane roșii și fresce. Aici se pune legenda labirintului și a Minotaurului. E singurul loc din Creta pe care îl știe toată lumea înainte să vină.',
    cumAjungi: '5 km sud de Heraklion, ~1 h din Amoudara. Deschis 08:00–20:00, ultima intrare 19:30.',
    capcane: 'Zero umbră și piatră care reflectă căldura. Reconstrucțiile în beton ale lui Evans sunt controversate — un ghid la intrare (+30 min) schimbă complet vizita.',
    deLuat: 'Pălărie, apă, și venit dimineața. Se potrivește perfect joi, înainte de masă.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Knossos+Palace',
  },
  {
    id: 'muzeul-heraklion',
    nume: 'Muzeul Arheologic din Heraklion',
    tip: 'istorie',
    zona: 'centru',
    dinVest: 135, dinEst: 60,
    subtitlu: 'Unde stau lucrurile scoase de la Knossos',
    durata: '1 h 30 min',
    costCenti: 1200,
    costText: '12 €; 30 € combinat cu Knossos',
    deCe: 'Cea mai bună colecție minoică din lume: frescele adevărate de la Knossos (la sit sunt copii), discul de la Phaistos, zeițele cu șerpi. La răcoare, cu aer condiționat — bun exact la ora la care afară nu se mai poate sta.',
    cumAjungi: 'În centrul Heraklionului, la 10 minute pe jos de Peskesi.',
    capcane: 'Se vizitează după Knossos, nu înainte — altfel situl pare gol.',
    deLuat: 'Varianta pentru joi, dacă e prea cald pentru altceva.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Heraklion+Archaeological+Museum',
  },
  {
    id: 'heraklion-centru',
    nume: 'Centrul vechi din Heraklion și fortul Koules',
    tip: 'sat',
    zona: 'centru',
    dinVest: 135, dinEst: 60,
    subtitlu: 'Ultimele ore, între masă și aeroport',
    durata: '1–2 h',
    costCenti: 400,
    costText: 'Gratis de umblat; Koules 4 €',
    deCe: 'Fortăreața venețiană de la capătul digului, fântâna cu lei, piața 25 Martie, zidurile orașului și mormântul lui Kazantzakis, cu priveliște peste tot orașul. Se face pe jos, în cerc, într-o oră.',
    cumAjungi: 'Peskesi e chiar în centru — tot ce e aici e la 10 minute pe jos.',
    capcane: 'Joi, nu vă întindeți: mașina trebuie predată.',
    deLuat: 'Ultimele suveniruri de aici, nu de la aeroport.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Koules+Fortress+Heraklion',
  },
  // ──────────────── adăugate la a doua trecere ────────────────
  {
    id: 'aptera',
    nume: 'Aptera',
    tip: 'istorie',
    zona: 'vest',
    ascuns: true,
    dinVest: 35, dinEst: null,
    subtitlu: 'Cisterne romane intacte, deasupra golfului Souda',
    durata: '1–2 h',
    costCenti: 1000,
    costText: '10 €/adult (5 € redus), include și fortul otoman',
    deCe: 'Un oraș antic pe un platou, cu vedere peste tot golful Souda. Piesa de rezistență sunt două cisterne romane cu bolți triple, păstrate aproape întregi — se intră în ele și e răcoare și ecou. Aproape nimeni nu se oprește, deși e la 400 de metri de șoseaua națională.',
    cumAjungi: '13 km est de Chania, chiar lângă ieșirea de pe drumul național spre est. Deschis zilnic 08:00–20:00 între aprilie și octombrie.',
    capcane: 'Zero umbră pe platou. Biletul de 10 € pare mult pentru cât e de mic situl, dar cisternele îl merită.',
    deLuat: 'Oprirea perfectă în prima oră a zilei de marți, când oricum plecați spre est.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Ancient+Aptera+Crete',
  },
  {
    id: 'arkadi',
    nume: 'Mănăstirea Arkadi',
    tip: 'istorie',
    zona: 'vest',
    vedeta: true,
    dinVest: 100, dinEst: null,
    subtitlu: 'Simbolul național al Cretei',
    durata: '1–2 h',
    costCenti: 300,
    costText: '3 €/adult, gratis sub 16 ani',
    deCe: 'În noiembrie 1866, cu mănăstirea înconjurată de trupe otomane și sute de femei și copii refugiați înăuntru, apărătorii au dat foc depozitului de praf de pușcă și au sărit în aer, ca să nu cadă prizonieri. Evenimentul a mișcat toată Europa. Fațada e Renaștere cretană pură, iar locul e liniștit într-un fel pe care nu-l are niciun alt loc din insulă.',
    cumAjungi: '23 km sud-est de Rethymno, pe un drum bun printre măslini. Din Maleme, ~1 h 40 min cu tot cu ocolul.',
    capcane: 'E o mănăstire funcțională: umeri și genunchi acoperiți. Ocolul de la drumul național adaugă vreo 50 de minute dus-întors.',
    deLuat: 'Dacă marți vreți un singur lucru care nu e plajă, ăsta e.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Arkadi+Monastery+Crete',
  },
  {
    id: 'malia',
    nume: 'Palatul minoic Malia',
    tip: 'istorie',
    zona: 'est',
    ascuns: true,
    dinVest: null, dinEst: 35,
    subtitlu: 'Al treilea palat minoic, chiar lângă șosea',
    durata: '1 h',
    costCenti: 600,
    costText: '~6 €/adult',
    deCe: 'Al treilea palat minoic ca mărime, după Knossos și Phaistos — dar fără reconstrucțiile în beton ale lui Evans și fără autocarele de la Knossos. Se vede curtea centrală, magaziile cu chiupuri uriașe și celebra piatră kernos. Pentru cine vrea să înțeleagă cum arăta de fapt un palat minoic, e mai lămuritor decât Knossos.',
    cumAjungi: '27 km de Agios Nikolaos, 41 de Heraklion, la 400 de metri de drumul național A90 — adică fix pe drumul vostru. Deschis 08:00–19:00 după 16 septembrie.',
    capcane: 'Nu confundați situl cu stațiunea Malia, care e altceva complet. Zero umbră.',
    deLuat: 'Se poate prinde marți, la sosirea în est, sau joi, în drum spre Heraklion.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Malia+Palace+archaeological+site+Crete',
  },
  {
    id: 'loutro',
    nume: 'Loutro',
    tip: 'barca',
    zona: 'vest',
    vedeta: true,
    dinVest: 80, dinEst: null,
    subtitlu: 'Un sat fără nicio mașină, la care se ajunge doar pe mare',
    durata: 'Jumătate de zi',
    costCenti: 2400,
    costText: '~12 €/adult feribotul dus-întors',
    deCe: 'Case albe și bougainvillea într-un golf în formă de potcoavă, pe coasta de sud. Nu are drum de acces — se ajunge numai cu barca sau pe jos. Asta înseamnă zero mașini, zero scutere, zero zgomot. Tavernele au mesele deasupra apei, iar marea libiană e mai caldă decât cea de nord.',
    cumAjungi: 'Din Chora Sfakion, feribotul face vreo 20 de minute. **Se leagă perfect cu cheile Imbros:** coborâți cheile dimineața, ieșiți la Komitades, ajungeți în Chora Sfakion și prindeți feribotul de 13:00.',
    capcane: 'Întoarcerea vă aduce în Chora Sfakion pe la 18:00–19:00, plus 1 h 20 min de condus până în Maleme. E o zi lungă, dar plină.',
    deLuat: 'Verificați orarul feribotului în dimineața aceea — se schimbă după vânt.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Loutro+Crete',
  },
  {
    id: 'stavros',
    nume: 'Stavros',
    tip: 'plaja',
    zona: 'vest',
    dinVest: 45, dinEst: null,
    subtitlu: 'Plaja din „Zorba grecul", sub un munte de calcar',
    durata: 'Jumătate de zi',
    costCenti: 0,
    costText: 'Gratis; șezlonguri ~8 €',
    deCe: 'Un golf aproape rotund, închis de un perete de calcar care cade drept în apă — arată ca un lac, nu ca marea. Aici s-a filmat în 1964 scena de sirtaki cu Anthony Quinn din „Zorba grecul". Apa e mică și liniștită pe zeci de metri.',
    cumAjungi: 'La capătul peninsulei Akrotiri, ~45 de minute din Maleme.',
    capcane: 'Fiind închis, golful se încălzește și apa nu e la fel de limpede ca în vest. Se combină bine cu mănăstirea Agia Triada, la 15 minute.',
    deLuat: 'O variantă blândă pentru o după-amiază, fără drum lung.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Stavros+Beach+Akrotiri+Crete',
  },
  {
    id: 'agia-triada',
    nume: 'Mănăstirea Agia Triada',
    tip: 'istorie',
    zona: 'vest',
    ascuns: true,
    dinVest: 40, dinEst: null,
    subtitlu: 'Renaștere cretană în mijlocul măslinilor',
    durata: '1 h',
    costCenti: 300,
    costText: '~3 €/adult',
    deCe: 'Ridicată în secolul XVII de doi frați dintr-o familie venețiană, e unul dintre cele mai frumoase exemple de Renaștere cretană: fațadă cu coloane, curte cu portocali, bibliotecă veche. Călugării fac ulei de măsline și vin, care se cumpără la poartă.',
    cumAjungi: 'Peninsula Akrotiri, ~40 de minute din Maleme, la 15 minute de plaja Stavros.',
    capcane: 'Mănăstire funcțională — umeri și genunchi acoperiți.',
    deLuat: 'Uleiul lor e un suvenir mai bun decât orice din aeroport.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Agia+Triada+Tzagaroli+Monastery+Crete',
  },
  {
    id: 'chrissi',
    nume: 'Insula Chrissi',
    tip: 'barca',
    zona: 'est',
    dinVest: null, dinEst: 50,
    subtitlu: 'Nisip alb și o pădure de cedri, în marea libiană',
    durata: 'Ziua întreagă',
    costCenti: 4000,
    costText: '~40 €/adult vaporul (6 h în total)',
    deCe: 'O insuliță nelocuită la 15 km în largul mării libiene, cu nisip alb-auriu, apă de un turcoaz aproape indecent și o pădure de cedri libanezi vechi de secole care crește direct din nisip. Arată ca Caraibele și e rezervație protejată.',
    cumAjungi: 'Vaporul pleacă din portul Ierapetra pe la 10:45–11:00. Traversarea ține o oră, pe insulă stați vreo patru. Ierapetra e la ~50 de minute din Amoudara.',
    capcane: 'Zi întreagă, deci intră în concurență cu Spinalonga. Pe insulă nu e nimic: fără umbră naturală în afara cedrilor (sub care e interzis să stai), fără magazin. Se calcă doar pe potecile marcate.',
    deLuat: 'Apă multă, mâncare, umbrelă. Dacă alegeți asta, Spinalonga rămâne pe joi dimineață.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Chrissi+Island+Crete',
  },
  // ──────────── coasta de sud, a treia trecere ────────────
  {
    id: 'kourtaliotiko',
    nume: 'Cheile Kourtaliotiko',
    tip: 'munte',
    zona: 'vest',
    vedeta: true,
    cerut: true,
    dinVest: 105, dinEst: 135,
    subtitlu: 'Cascadă la capătul unei scări abrupte',
    durata: '1–2 h',
    costCenti: 500,
    costText: '5 €/persoană intrarea',
    deCe: 'Șapte kilometri de defileu tăiat în stâncă roșiatică, prin care vântul urlă — de aici i se trage numele, „kourtala" înseamnă bubuit. De la șosea cobori vreo două sute de trepte până la cascada Kourtaliotis, care cade într-un bazin verde unde se poate intra. Vulturii se rotesc deasupra aproape tot timpul.',
    cumAjungi: 'Se parchează lângă arcada de piatră de la marginea drumului, între Koxare și Plakias. Parcarea e mică și gratuită — veniți înainte de 10:00 sau rămâneți pe marginea șoselei.',
    capcane: 'Treptele sunt abrupte și alunecoase la coborâre, iar urcatul înapoi e partea grea. Apa e tăioasă, chiar și în septembrie. Nu e drum pentru șlapi.',
    deLuat: 'Adidași, apă, și un prosop dacă vreți să intrați sub cascadă. Se leagă direct cu Preveli, la 15 minute mai jos.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Kourtaliotiko+Gorge+Crete',
  },
  {
    id: 'preveli',
    nume: 'Preveli',
    tip: 'plaja',
    zona: 'vest',
    vedeta: true,
    cerut: true,
    dinVest: 120, dinEst: 150,
    subtitlu: 'Un râu cu palmieri care se varsă în mare',
    durata: '2–3 h pe plajă',
    costCenti: 200,
    costText: 'Plaja gratis; parcarea ~2 €',
    deCe: 'La capătul cheilor Kourtaliotiko, un râu curge printr-o pădure de palmieri și se varsă direct în marea libiană. Poți înota în apă sărată și, la zece metri mai încolo, să urci pe râu prin apă dulce, între palmieri. Nu seamănă cu nimic altceva din Creta.',
    cumAjungi: 'Din parcarea de sus se coboară pe o potecă abruptă, 12–20 de minute. Se poate ajunge și cu barca din Plakias, dacă nu vreți coborârea.',
    capcane: 'Urcușul înapoi, pe căldură, e serios — socotiți-l înainte, nu după. Plaja n-are umbră naturală în afara palmierilor, iar șezlongurile sunt puține. În 2010 un incendiu a ars pădurea; s-a refăcut, dar nu e la fel de deasă ca în poze vechi.',
    deLuat: 'Pantofi buni pentru coborâre, apă, pălărie. Cu cheile Kourtaliotiko, e o zi întreagă din Maleme — plecare la 08:00.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Preveli+Beach+Crete',
  },
  {
    id: 'kalypso',
    nume: 'Kalypso',
    tip: 'plaja',
    zona: 'vest',
    ascuns: true,
    dinVest: 115, dinEst: 145,
    subtitlu: 'Varianta la Preveli, fără coborâre',
    durata: '2–3 h',
    costCenti: 0,
    costText: 'Acces cu taxă mică pe drumul privat',
    deCe: 'Un golf mic între stânci roșii, cu apă adâncă și limpede, la câteva minute de Preveli. Se ajunge aproape cu mașina până la apă, deci e alegerea bună pentru cine nu vrea coborârea de douăzeci de minute de la Preveli. Are un bar și scări de fier în stâncă pentru intrat în apă.',
    cumAjungi: 'Pe drumul dintre Plakias și Preveli, se face dreapta pe un drum privat semnalizat.',
    capcane: 'Nu e nisip, ci stânci și pietriș, cu intrare adâncă în apă — nu e de copii mici. Mai mic decât pare în fotografii.',
    deLuat: 'Papuci de apă. De luat în calcul doar dacă mergeți oricum spre Preveli.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Kalypso+Beach+Plakias+Crete',
  },
  {
    id: 'georgioupolis',
    nume: 'Capela Agios Nikolaos, Georgioupolis',
    tip: 'sat',
    zona: 'vest',
    ascuns: true,
    cerut: true,
    dinVest: 55, dinEst: 130,
    subtitlu: 'Biserica de pe dig, singură în mare',
    durata: '1–2 h',
    costCenti: 0,
    costText: 'Gratis',
    deCe: 'Capela Agios Nikolaos stă pe un dig îngust de piatră care intră vreo sută de metri în mare — se merge pe jos până la ea, cu valurile de-o parte și de alta. E una dintre cele mai fotografiate imagini din Creta, și e la cinci minute de lacul Kournas.',
    cumAjungi: 'Direct pe drumul național, exact pe traseul de marți. Ieșirea e comună cu cea spre Kournas.',
    capcane: 'Pe vânt, digul e udat de valuri și devine alunecos — atunci nu se merge pe el. Satul în sine e turistic și fără caracter; opriți-vă pentru capelă, nu pentru sat.',
    deLuat: 'Cinci minute de oprire care nu costă nimic, marți. Se combină cu Kournas.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Agios+Nikolaos+chapel+Georgioupolis+Crete',
  },
  {
    id: 'margarites',
    nume: 'Margarites',
    tip: 'sat',
    zona: 'vest',
    ascuns: true,
    dinVest: 90, dinEst: 115,
    subtitlu: 'Satul olarilor, de cinci secole',
    durata: '1–2 h',
    costCenti: 0,
    costText: 'Gratis de umblat',
    deCe: 'Un sat de munte cu vedere peste văi de măslini, în care se face ceramică de cinci sute de ani. Atelierele sunt deschise spre stradă și meșterii lucrează la roată în fața ta. Se cumpără direct de la ei, la prețuri care n-au nimic de-a face cu magazinele de pe litoral.',
    cumAjungi: '~30 de minute de la Rethymno, la 20 de minute abatere de pe drumul de marți.',
    capcane: 'Ce cumperi trebuie să ajungă acasă întreg — cereți ambalaj bun și puneți-l în bagajul de mână, nu în cală.',
    deLuat: 'Cel mai bun suvenir din Creta, dacă vreți altceva decât ulei și raki.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Margarites+pottery+village+Crete',
  },
  // ──────────── a patra trecere ────────────
  {
    id: 'triopetra',
    nume: 'Triopetra',
    tip: 'plaja',
    zona: 'vest',
    vedeta: true,
    cerut: true,
    dinVest: 135, dinEst: 160,
    subtitlu: 'Trei stânci și un kilometru de plajă aproape goală',
    durata: 'Ziua întreagă',
    costCenti: 0,
    costText: 'Gratis; șezlonguri la tavernă',
    deCe: 'Numele înseamnă „trei pietre", după stâncile care ies din mare la capătul plajei. Sunt formațiuni ciudate, ca niște foi uriașe de piatră stivuite una peste alta — și se poate ajunge la ele pe jos, ca să le urci și să le pipăi. **Alegeți plaja lungă, de un kilometru, nu plajele mici de pe partea cealaltă** — acolo se simte spațiul și lipsa aglomerației.',
    cumAjungi: 'Pe coasta de sud, între Plakias și Matala. O oră de la Rethymno, o oră de la Plakias, 1 h 10 min de la Matala. Se coboară de pe drumul principal pe un drum de munte.',
    capcane: 'E departe — puțin mai la o parte decât tot restul. La capătul plajei, spre stânci, e o singură tavernă, cu șezlonguri. În rest, nimic.',
    deLuat: 'O zi întreagă, dacă vreți o plajă pe care chiar să fiți singuri. Se leagă cu Preveli și Kourtaliotiko, toate pe aceeași coastă.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Triopetra+beach+Crete',
  },
  {
    id: 'melidoni',
    nume: 'Peștera Melidoni',
    tip: 'munte',
    zona: 'vest',
    ascuns: true,
    dinVest: 95, dinEst: 105,
    subtitlu: 'Sala uriașă pe care n-o știe aproape nimeni',
    durata: '1 h',
    costCenti: 500,
    costText: '5 €/persoană',
    deCe: 'Diferența față de peștera lui Zeus e uriașă: acolo sunt cozi, aici poți fi singur. Are mai puține stalactite, dar **sala principală e impresionantă ca dimensiune** și accesul e mult mai ușor. Are și o istorie grea: în 1824, sute de localnici ascunși înăuntru au fost asfixiați de turci — de aici osuarul din peșteră.',
    cumAjungi: 'Pe coasta de nord, la jumătatea drumului dintre Heraklion și Rethymno, lângă Bali. Abatere scurtă de pe drumul rapid; doar ultimele sute de metri urcă pe munte.',
    capcane: 'Circa o sută de trepte înăuntru. Vara e deschisă 09:00–17:30, iarna 10:00–16:00 — verificați pe melidoni.gr înainte.',
    deLuat: 'Pantofi închiși și o bluză: înăuntru e răcoare. Cade fix pe drumul de marți.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Melidoni+Cave+Crete',
    web: 'https://www.melidoni.gr/cave-cub9',
  },
  {
    id: 'zeus',
    nume: 'Peștera lui Zeus (Psychro)',
    tip: 'munte',
    zona: 'est',
    dinVest: null, dinEst: 70,
    subtitlu: 'Unde spune mitul că s-a născut Zeus',
    durata: '1–2 h',
    costCenti: 600,
    costText: '6 €/persoană',
    deCe: 'La marginea platoului Lasithi, în satul Psychro, o peșteră cu stalactite în care, spune mitul, Rhea l-a ascuns pe Zeus ca să nu-l înghită Cronos. S-au găsit acolo ofrande din epoca minoică, deci locul chiar era considerat sfânt acum patru mii de ani.',
    cumAjungi: '~1 h 10 min din Amoudara, pe serpentine, urcând pe platoul Lasithi. De la parcare, 15–20 de minute de urcat pe o potecă pietruită.',
    capcane: 'Poteca de urcat e pietruită și alunecoasă, iar înăuntru scările sunt umede. E cel mai aglomerat obiectiv din estul insulei — la Melidoni, în vest, veți fi aproape singuri.',
    deLuat: 'Pantofi închiși cu talpă bună. Se face împreună cu turul platoului Lasithi.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Psychro+Cave+Zeus+Crete',
  },
  {
    id: 'muzeul-muzical',
    nume: 'Muzeul instrumentelor muzicale',
    tip: 'istorie',
    zona: 'centru',
    ascuns: true,
    dinVest: null, dinEst: 70,
    subtitlu: 'Peste 250 de instrumente, adunate din toată lumea',
    durata: '1 h',
    costCenti: 0,
    costText: 'Intrare liberă',
    deCe: 'Atelierul Labyrinth, fondat de muzicianul irlandez Ross Daly, adăpostește într-o casă veche din satul Houdetsi peste 250 de instrumente tradiționale strânse de el în timpul călătoriilor — singura colecție de felul ăsta din Grecia. Nu e un muzeu cu vitrine și liniște, e un loc unde se ține școală de muzică.',
    cumAjungi: 'Satul Houdetsi, la ~20 de minute sud de Heraklion, aproape de Archanes și de cramele din Peza.',
    capcane: 'Program mai ales în zilele lucrătoare, cu ore mai lungi vara. Sunați sau verificați înainte — e un atelier, nu un muzeu de stat.',
    deLuat: 'Se leagă bine cu Knossos și cu o degustare de vinuri în Peza, joi.',
    harta: 'https://www.google.com/maps/search/?api=1&query=Labyrinth+Musical+Workshop+Houdetsi+Crete',
  },
];

export function locul(id) {
  return LOCURI.find((l) => l.id === id) || null;
}

export function locuriDinZona(zona) {
  return LOCURI.filter((l) => l.zona === zona);
}

/** Minutele de condus din baza potrivită zonei în care dormim. */
export function drumDin(loc, baza) {
  if (baza === 'est') return loc.dinEst;
  if (baza === 'vest') return loc.dinVest;
  return null;
}

export const VEDETE = LOCURI.filter((l) => l.vedeta);
export const ASCUNSE = LOCURI.filter((l) => l.ascuns);
export const CERUTE = LOCURI.filter((l) => l.cerut);

// ─────────────────────────── Topul locurilor ───────────────────────────
//
// „Ce trebuie văzut", ordonat pentru EXCURSIA ASTA — nu un clasament absolut
// al Cretei. Un loc care cere patru ore de condus dintr-o bază în care stăm
// două nopți pierde în fața unuia la fel de frumos și la douăzeci de minute.

const TOP = {
  balos: { rang: 1, motiv: 'Imaginea pentru care lumea vine în Creta, iar barca din Kissamos pleacă la 40 de minute de cazarea voastră. Nimic altceva din vest nu bate asta.' },
  spinalonga: { rang: 2, motiv: 'Cel mai puternic loc din est, și exact plimbarea cu barca pe care ați cerut-o. Traversarea din Plaka ține zece minute, iar insula rămâne cu voi mult după.' },
  chania: { rang: 3, motiv: 'Cel mai frumos oraș vechi al insulei, la 25 de minute. O seară acolo valorează cât o zi de drum în altă parte.' },
  knossos: { rang: 4, motiv: 'Singurul loc din Creta pe care îl știe toată lumea înainte să vină — și pică perfect joi dimineață, pe drumul spre aeroport.' },
  voulisma: { rang: 5, motiv: 'Cea mai frumoasă plajă din estul insulei, la 20 de minute de a doua cazare. Ați cerut-o, și merită.' },
  imbros: { rang: 6, motiv: 'Traseul montan care chiar încape într-o zi: opt kilometri de defileu, fără nimic tehnic, în adidași. Și se leagă cu Loutro.' },
  loutro: { rang: 7, motiv: 'Un sat fără nicio mașină, la care se ajunge doar pe mare. Prins după cheile Imbros, cu feribotul de 13:00, face cea mai bună zi a excursiei.' },
  elafonisi: { rang: 8, motiv: 'Cea mai faimoasă plajă a Cretei. Ar fi fost mai sus dacă drumul n-ar fi două ore de serpentine, dus — și dacă n-ar cădea în aceeași zi cu Balos.' },
  lasithi: { rang: 9, motiv: 'Cealaltă față a insulei: un platou la 850 m, cu mori de vânt și sate care arată ca acum șaptezeci de ani.' },
  preveli: { rang: 10, motiv: 'Un râu cu palmieri care se varsă în mare — nu seamănă cu nimic altceva din Creta. Cerut de voi, și merită ziua întreagă pe care o cere.' },
  triopetra: { rang: 11, motiv: 'Un kilometru de plajă pe care chiar poți fi singur, și trei stânci stivuite ca niște foi de piatră, pe care se urcă. Cerut de voi — și da, e departe.' },
  arkadi: { rang: 12, motiv: 'Pentru cretani, locul ăsta e Crete. În 1866 apărătorii au aruncat mănăstirea în aer ca să nu cadă prizonieri. E la 50 de minute abatere de pe drumul vostru de marți.' },
  falassarna: { rang: 13, motiv: 'Cel mai bun apus din Creta, la 40 de minute. Ieftin ca efort, mare ca amintire.' },
  kournas: { rang: 14, motiv: 'Cade fix la jumătatea drumului de marți. O oprire care transformă un transfer de trei ore într-o zi.' },
};

// Mai puțin știute, dar care merită dacă rămâne timp.
const COMORI = {
  aptera: 'Cisterne romane cu bolți intacte, la 400 m de șoseaua pe care oricum mergeți marți.',
  malia: 'Al treilea palat minoic, fără reconstrucții în beton și fără autocare. Chiar lângă drumul spre est.',
  seitan: 'O crăpătură în stâncă, cu apă turcoaz — dar coborârea e serioasă.',
  richtis: 'Cel mai verde traseu din est, cu o cascadă de 20 m la capăt.',
  mochlos: 'Șapte case, patru taverne și o insuliță minoică la 200 de metri.',
  kritsa: 'Cele mai bine păstrate fresce bizantine din Creta.',
  argiroupoli: 'Cascade sub platani bătrâni, cu câteva grade mai răcoare.',
  therisos: 'Chei pe care le treci cu mașina, fără să cobori.',
  kamini: 'Cinci golfuri de pietriș fără absolut nimic pe ele — ați cerut-o.',
  'agia-triada': 'Renaștere cretană între măslini; călugării vând uleiul lor la poartă.',
  melidoni: 'O sală uriașă de peșteră în care poți fi singur — spre deosebire de peștera lui Zeus.',
  'muzeul-muzical': '250 de instrumente din toată lumea, într-o casă de sat. Intrare liberă.',
  kourtaliotiko: 'Două sute de trepte până la o cascadă în care se poate intra. Merge mână în mână cu Preveli.',
  georgioupolis: 'O capelă pe un dig de piatră, la o sută de metri în mare. Cinci minute, zero abatere.',
  margarites: 'Ateliere de olărit deschise spre stradă, de cinci secole.',
  kalypso: 'Varianta la Preveli pentru cine nu vrea coborârea de douăzeci de minute.',
  'plaja-hotel': 'Șapte minute pe jos de cazare, cu șezlonguri gratuite la Wave.',
};

for (const l of LOCURI) {
  const t = TOP[l.id];
  if (t) { l.rang = t.rang; l.deCeInTop = t.motiv; }
  if (COMORI[l.id]) l.deCeComoara = COMORI[l.id];
}

/** Topul, în ordine. */
export const TOP_LOCURI = LOCURI
  .filter((l) => l.rang)
  .sort((a, b) => a.rang - b.rang);

export const COMORI_ASCUNSE = LOCURI.filter((l) => l.deCeComoara);
