// Fotografiile locurilor. Descărcate de pe Wikimedia Commons și micșorate la
// 640 px, ca să intre în cache-ul offline fără să umfle prima încărcare.
//
// Licențele cer atribuire, de aceea fiecare intrare își poartă autorul, licența
// și legătura spre original — iar interfața le afișează sub poză.
//
// Generat cu tools/ — dacă schimbi o poză, schimbă și creditul.

export const POZE = {
  'balos': {
    fisier: 'assets/locuri/balos.jpg',
    descriere: 'Laguna Balos, cu insula Gramvousa în fundal',
    autor: 'Robin & Bazylek',
    licenta: 'CC BY 2.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Gramvousa_viewed_from_the_lagoon_of_Balos.jpg',
  },
  'elafonisi': {
    fisier: 'assets/locuri/elafonisi.jpg',
    descriere: 'Laguna de la Elafonisi',
    autor: 'jarekgrafik',
    licenta: 'CC0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Greece_Crete_Elafonisi_Beach_The_Sun_Holidays.jpg',
  },
  'falassarna': {
    fisier: 'assets/locuri/falassarna.jpg',
    descriere: 'Plaja Falassarna',
    autor: 'Pavel Špindler',
    licenta: 'CC BY 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Falassarna_-_Kr%C3%A9ta_-_panoramio_(1).jpg',
  },
  'chania': {
    fisier: 'assets/locuri/chania.jpg',
    descriere: 'Portul venețian din Chania',
    autor: 'Lapplaender',
    licenta: 'CC BY-SA 3.0 de',
    sursa: 'https://commons.wikimedia.org/wiki/File:Chania_-_Venetian_harbor_2.jpg',
  },
  'imbros': {
    fisier: 'assets/locuri/imbros.jpg',
    descriere: 'Cheile Imbros',
    autor: 'Aivin Gast',
    licenta: 'CC BY-SA 4.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Imbros_Gorge,_Crete.jpg',
  },
  'samaria': {
    fisier: 'assets/locuri/samaria.jpg',
    descriere: 'Cheile Samaria',
    autor: 'C messier',
    licenta: 'CC BY-SA 4.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:%CE%A6%CE%B1%CF%81%CE%AC%CE%B3%CE%B3%CE%B9_%CE%A3%CE%B1%CE%BC%CE%B1%CF%81%CE%B9%CE%AC%CF%82_3754.jpg',
  },
  'kolymbari': {
    fisier: 'assets/locuri/kolymbari.jpg',
    descriere: 'Mănăstirea Gonia, la Kolymbari',
    autor: 'Mik@el',
    licenta: 'CC BY 4.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Sea_view_of_Gonia_Monastery_and_Orthodox_Academy_of_Crete,_Kolymvari,_Platanias,_Crete,_Greece.jpg',
  },
  'therisos': {
    fisier: 'assets/locuri/therisos.jpg',
    descriere: 'Cheile Therisos',
    autor: 'Aeleftherios',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:TherisoGorge.JPG',
  },
  'kournas': {
    fisier: 'assets/locuri/kournas.jpg',
    descriere: 'Lacul Kournas',
    autor: 'Taxiarchos228',
    licenta: 'FAL',
    sursa: 'https://commons.wikimedia.org/wiki/File:Kreta_-_Kournas-See.jpg',
  },
  'rethymno': {
    fisier: 'assets/locuri/rethymno.jpg',
    descriere: 'Portul venețian din Rethymno',
    autor: 'Wladyslaw',
    licenta: 'FAL',
    sursa: 'https://commons.wikimedia.org/wiki/File:Rethymno_-_Venezianischer_Hafen1.jpg',
  },
  'kamini': {
    fisier: 'assets/locuri/kamini.jpg',
    descriere: 'Așezarea minoică Gournia, chiar deasupra plajelor Kamini',
    autor: 'Lourakis (talk)',
    licenta: 'Public domain',
    sursa: 'https://commons.wikimedia.org/wiki/File:GourniaMinoanPalace.jpg',
  },
  'spinalonga': {
    fisier: 'assets/locuri/spinalonga.jpg',
    descriere: 'Insula Spinalonga, văzută dinspre Elounda',
    autor: 'Ggia',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:20090620_Spinalogka_Elounta_panoramic_view_from_the_mountain.jpg',
  },
  'agios-nikolaos': {
    fisier: 'assets/locuri/agios-nikolaos.jpg',
    descriere: 'Agios Nikolaos',
    autor: 'Marc Ryckaert (MJJR)',
    licenta: 'CC BY 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Agios_Nikolaos_R01.jpg',
  },
  'plaka-elounda': {
    fisier: 'assets/locuri/plaka-elounda.jpg',
    descriere: 'Golful Elounda',
    autor: 'George Groutas',
    licenta: 'CC BY 2.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Elounda_02.jpg',
  },
  'lasithi': {
    fisier: 'assets/locuri/lasithi.jpg',
    descriere: 'Platoul Lasithi',
    autor: 'Marc Ryckaert (MJJR)',
    licenta: 'CC BY 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Lasithi_R01.jpg',
  },
  'kritsa': {
    fisier: 'assets/locuri/kritsa.jpg',
    descriere: 'Biserica Panagia Kera, lângă Kritsa',
    autor: 'Ahanta',
    licenta: 'Public domain',
    sursa: 'https://commons.wikimedia.org/wiki/File:Panagia_Kera_2011.jpg',
  },
  'richtis': {
    fisier: 'assets/locuri/richtis.jpg',
    descriere: 'Cascada din cheile Richtis',
    autor: 'Kostdro',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Richtis_waterfall_at_Richtis_gorge_in_Crete.jpg',
  },
  'mochlos': {
    fisier: 'assets/locuri/mochlos.jpg',
    descriere: 'Satul Mochlos',
    autor: 'Gueroe',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Kreta_r_08_039.jpg',
  },
  'vai': {
    fisier: 'assets/locuri/vai.jpg',
    descriere: 'Pădurea de palmieri de la Vai',
    autor: 'Marc Ryckaert (MJJR)',
    licenta: 'CC BY 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Vai_R01.jpg',
  },
  'knossos': {
    fisier: 'assets/locuri/knossos.jpg',
    descriere: 'Intrarea de nord a palatului Knossos',
    autor: 'Moonik',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Knossos_north_entrance,_Crete_001.JPG',
  },
  'muzeul-heraklion': {
    fisier: 'assets/locuri/muzeul-heraklion.jpg',
    descriere: 'Exponat din Muzeul Arheologic din Heraklion',
    autor: 'C messier',
    licenta: 'CC BY-SA 4.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:%CE%9F%CE%BC%CE%BF%CE%AF%CF%89%CE%BC%CE%B1_%CE%BD%CE%B1%CE%BF%CF%8D_%CE%BC%CE%B5_%CE%B1%CE%BD%CE%AC%CE%B3%CE%BB%CF%85%CF%86%CE%B7_%CE%BC%CE%BF%CF%81%CF%86%CE%AE_%CE%91%CE%9C%CE%97_9057.jpg',
  },
  'heraklion-centru': {
    fisier: 'assets/locuri/heraklion-centru.jpg',
    descriere: 'Fortăreața Koules, Heraklion',
    autor: 'Bernard Gagnon',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Venitian_Fortress_of_Koules.jpg',
  },
  'amoudara-plaja': {
    fisier: 'assets/locuri/amoudara-plaja.jpg',
    descriere: 'Golful Mirabello, pe care stă Amoudara',
    autor: 'Marco ed Emanuela',
    licenta: 'CC BY 2.5',
    sursa: 'https://commons.wikimedia.org/wiki/File:Crete,_Gulf_of_Mirabella_from_Gournia.jpg',
  },
  'seitan': {
    fisier: 'assets/locuri/seitan.jpg',
    descriere: 'Golful Seitan Limania',
    autor: 'Olhaz',
    licenta: 'Public domain',
    sursa: 'https://commons.wikimedia.org/wiki/File:Chania_-_Seitan_Limania.jpg',
  },
  'argiroupoli': {
    fisier: 'assets/locuri/argiroupoli.jpg',
    descriere: 'Argiroupoli',
    autor: 'Olaf Tausch',
    licenta: 'CC BY 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Argyroupoli_01.JPG',
  },
  'voulisma': {
    fisier: 'assets/locuri/voulisma.jpg',
    descriere: 'Golful Istron, în care se află plaja Voulisma',
    autor: 'Sokoban',
    licenta: 'Public domain',
    sursa: 'https://commons.wikimedia.org/wiki/File:Istron_Bay_01.jpg',
  },
  'plaja-hotel': {
    fisier: 'assets/locuri/plaja-hotel.jpg',
    descriere: 'O plajă organizată de pe coasta de nord — a voastră arată la fel',
    autor: 'Moonik',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Platanias_near_Rethymno,_Crete_001.JPG',
  },
  'aptera': {
    fisier: 'assets/locuri/aptera.jpg',
    descriere: 'Cisternele romane de la Aptera',
    autor: 'Aeleftherios',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Aptera_cistern.JPG',
  },
  'arkadi': {
    fisier: 'assets/locuri/arkadi.jpg',
    descriere: 'Mănăstirea Arkadi',
    autor: 'Bernard Gagnon',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Arkadi_Monastery_-_Apses_of_the_church.jpg',
  },
  'malia': {
    fisier: 'assets/locuri/malia.jpg',
    descriere: 'Palatul minoic de la Malia',
    autor: 'Raintheone',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Minoan_Palace_of_Malia_2.jpg',
  },
  'loutro': {
    fisier: 'assets/locuri/loutro.jpg',
    descriere: 'Golful satului Loutro',
    autor: 'Pufacz',
    licenta: 'Public domain',
    sursa: 'https://commons.wikimedia.org/wiki/File:Harbour_in_Loutro_Crete_Greece.jpg',
  },
  'chrissi': {
    fisier: 'assets/locuri/chrissi.jpg',
    descriere: 'Insula Chrissi',
    autor: 'Paul',
    licenta: 'CC BY-SA 2.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Chrissi-travellingrunes-029.jpg',
  },
  'stavros': {
    fisier: 'assets/locuri/stavros.jpg',
    descriere: 'Golful Stavros, în Akrotiri',
    autor: 'G Da',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Crystal_water_of_Stavros_beach_-_Crete,_Greece_-_panoramio.jpg',
  },
  'agia-triada': {
    fisier: 'assets/locuri/agia-triada.jpg',
    descriere: 'Mănăstirea Agia Triada Tsagarolon',
    autor: 'Wolfgang Sauber',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Agia_Triada_-_Klosterhof_-_Kapelle_1.jpg',
  },
  'kourtaliotiko': {
    fisier: 'assets/locuri/kourtaliotiko.jpg',
    descriere: 'Cheile Kourtaliotiko',
    autor: 'No machine-readable author provided. Apeto assumed (based on copyright',
    licenta: 'CC BY-SA 2.5',
    sursa: 'https://commons.wikimedia.org/wiki/File:Kourtaliotiko_waterfall.jpg',
  },
  'preveli': {
    fisier: 'assets/locuri/preveli.jpg',
    descriere: 'Valea cu palmieri de la Preveli — râul Megalopotamos e panglica verde care coboară spre plajă',
    autor: 'Uoaei1',
    licenta: 'CC BY-SA 4.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Preveli_Palm_Beach_01.JPG',
  },
  'kalypso': {
    fisier: 'assets/locuri/kalypso.jpg',
    descriere: 'Golful Damnoni, vecin cu Kalypso — aceeași coastă, același fel de apă',
    autor: 'Olaf Tausch',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Damnoni,Ammoudi.jpg',
  },
  'georgioupolis': {
    fisier: 'assets/locuri/georgioupolis.jpg',
    descriere: 'Capela Agios Nikolaos, pe dig',
    autor: 'echiner1',
    licenta: 'CC BY-SA 2.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Agios_Nikolaos_Georgioupolis.jpg',
  },
  'margarites': {
    fisier: 'assets/locuri/margarites.jpg',
    descriere: 'Indicator ceramic spre atelierele de olărit din Margarites',
    autor: 'Dietmar Rabich',
    licenta: 'CC BY-SA 4.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Kreta_(GR),_Margarites,_Wegweiser_--_2023_--_8688.jpg',
  },
  'triopetra': {
    fisier: 'assets/locuri/triopetra.jpg',
    descriere: 'Plaja Triopetra, cu cele trei stânci',
    autor: 'Dieter Mueller, dino1948',
    licenta: 'CC BY-SA 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Triopetra_View_to.JPG',
  },
  'melidoni': {
    fisier: 'assets/locuri/melidoni.jpg',
    descriere: 'Peștera Melidoni',
    autor: 'Shadowgate from Novara, Italy',
    licenta: 'CC BY 2.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Melidoni_Cave.jpg',
  },
  'zeus': {
    fisier: 'assets/locuri/zeus.jpg',
    descriere: 'Peștera de la Psychro',
    autor: 'Pathwaygr',
    licenta: 'CC BY 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Diktaion_antron_(cave_of_Psychro)_01.jpg',
  },
  'muzeul-muzical': {
    fisier: 'assets/locuri/muzeul-muzical.jpg',
    descriere: 'Liră cretană — instrumentul de bază al colecției',
    autor: 'Lemur12',
    licenta: 'CC BY 3.0',
    sursa: 'https://commons.wikimedia.org/wiki/File:Cretan_lyra.jpg',
  },
};

export function poza(idLoc) {
  return POZE[idLoc] || null;
}
